export const SHOW_FORM_PROJECT = 'SHOW_FORM_PROJECT'
export const CHANGE_ALERT_ADD_PROJECT = 'CHANGE_ALERT_ADD_PROJECT'
export const ADD_PROJECT = 'ADD_PROJECT'

export const ADD_CLIENT = 'ADD_CLIENT'
